# Generated by Django 2.2.6 on 2019-10-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
